### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by augustine5644** [learn-co-curriculum/phase-0-completing-assignments-codegrade#4]
### Canvas Link

https://learning.flatironschool.com/courses/6611/assignments/224886?module_item_id=525442

### Concern

When following instructions in the first  prep assignment i am getting an error when i run the command npm install. (see error in additional context) 
I have made sure my node was installed properly
i have checked my version as well [opledople@DadsPC:~/Development/code/se-prep$ node -v
v18.13.0]
Not sure what to do here.

### Additional Context

opledople@DadsPC:~/Development/code/se-prep$ npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/opledople/Development/code/se-prep/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/opledople/Development/code/se-prep/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/opledople/.npm/_logs/2023-01-18T00_24_53_175Z-debug-0.log

**Comment by lizbur10** [comment]
Thanks for raising this issue. Based on your description, it sounds like the
issue may be related to your environment setup rather than with the lesson
itself or the instructions. The curriculum team monitors these issues so that we
can fix typos and bugs in the curriculum, but we aren't equipped to provide
support.

To get help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the
  [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)
  feature in Canvas to connect with a Technical Coach on the Academic Success
  Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
